---
title: "calcofi4r"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{calcofi4r}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
# devtools::document()
# devtools::install_local(here::here(), force=T) # install local
```

## Plot time series of an oceanographic variable

```{r setup}
library(calcofi4r) # devtools::load_all()

# get variables
(v <- get_variables())

# fetch time series data for the first variable from CalCOFI API
(d <- get_timeseries(v$table_field[1]))

# plot time series with the first variable
with(v[1,],
  plot_timeseries(
    # data and columns (from d)
    d, year, val_avg, val_sd,
    # plot attributes (from v)
    plot_title, plot_label, plot_color))
```

## Contour map a variable

```{r}
library(mapview)

# show first 6 rows of example data frame with temperature as variable
head(stations_t_degc)

# show bounding polygon
mapView(area_calcofi_extended)
```

```{r}
# generate contour polygon, aka isobands, using generalized additive model
v_ply <- tbl_to_contour_ply(
  df = stations_t_degc, ply = area_calcofi_extended)

# show generated 
mapView(v_ply, zcol="v", layer.name="temp(ºC)")
```


## Map interpolated oceanographic variable for a cruise

```{r}
# get cruises
(z <- get_cruises())

# get path of temporary file to store raster
(r_tif <- tempfile(fileext=".tif"))

# use second variable from previously fetched v
c(v$table_field[2], v$plot_label[2])

# fetch interpolated raster from CalCOFI API
get_raster(
  variable = v$table_field[2],
  cruise_id = "2020-01-05-C-33RL",
  depth_m_min = 0, depth_m_max = 200,
  out_tif = r_tif)

# read raster
r <- raster::raster(r_tif)

# plot raster
map_raster(r, v$plot_label[2])
```

```{r}
# cleanup by deleting temporary file
unlink(r_tif)
```

